sonar.projectKey=AXE-Hex_Horus
sonar.organization=axe-hex

# ده المسار اللي فيه الكود، سيبه زي ما هو عشان يفحص كل الملفات
sonar.sources=lib
sonar.tests=test

# لغة البرمجة
sonar.language=dart
sonar.sourceEncoding=UTF-8
