part of 'roles.dart';

// Permission sets here seed debug-only mock accounts. Production authorization
// reads `permissions` joined through `user_roles` and `role_permissions`.
final Map<UserRole, RoleInfo> roleRegistry = {
  UserRole.rector: const RoleInfo(
    role: UserRole.rector,
    category: RoleCategory.academicLeadership,
    nameEn: 'Rector / President',
    nameAr: 'مدير الجامعة',
    descriptionEn: 'University president with full academic oversight',
    descriptionAr: 'مدير الجامعة مع إشراف أكاديمي كامل',
    hierarchyLevel: 1,
    permissions: {
      RolePermission.manageColleges,
      RolePermission.manageDepartments,
      RolePermission.manageCourses,
      RolePermission.manageSchedules,
      RolePermission.approveEnrollments,
      RolePermission.adviseStudents,
      RolePermission.assignAdvisors,
      RolePermission.viewProfile,
      RolePermission.editOwnProfile,
      RolePermission.viewNotifications,
      RolePermission.createAnnouncements,
      RolePermission.createPost,
    },
  ),

  UserRole.dean: const RoleInfo(
    role: UserRole.dean,
    category: RoleCategory.academicLeadership,
    nameEn: 'Dean',
    nameAr: 'عميد الكلية',
    descriptionEn: 'Head of a college/faculty',
    descriptionAr: 'رئيس كلية أو مجمع أكاديمي',
    hierarchyLevel: 2,
    permissions: {
      RolePermission.manageDepartments,
      RolePermission.manageCourses,
      RolePermission.manageSchedules,
      RolePermission.approveEnrollments,
      RolePermission.adviseStudents,
      RolePermission.assignAdvisors,
      RolePermission.createAnnouncements,
      RolePermission.createPost,
      RolePermission.viewProfile,
      RolePermission.editOwnProfile,
      RolePermission.viewNotifications,
    },
  ),

  UserRole.departmentHead: const RoleInfo(
    role: UserRole.departmentHead,
    category: RoleCategory.academicLeadership,
    nameEn: 'Department Head',
    nameAr: 'رئيس القسم',
    descriptionEn: 'Head of an academic department',
    descriptionAr: 'رئيس قسم أكاديمي',
    hierarchyLevel: 3,
    permissions: {
      RolePermission.manageCourses,
      RolePermission.manageSchedules,
      RolePermission.approveEnrollments,
      RolePermission.manageTAs,
      RolePermission.createAnnouncements,
      RolePermission.createPost,
      RolePermission.viewProfile,
      RolePermission.editOwnProfile,
      RolePermission.viewNotifications,
    },
  ),

  UserRole.assistantHod: const RoleInfo(
    role: UserRole.assistantHod,
    category: RoleCategory.academicLeadership,
    nameEn: 'Assistant Head of Department',
    nameAr: 'مساعد رئيس القسم',
    descriptionEn: 'Assists the head of an academic department',
    descriptionAr: 'يساعد رئيس القسم الأكاديمي',
    hierarchyLevel: 4,
    permissions: {
      RolePermission.manageCourses,
      RolePermission.manageSchedules,
      RolePermission.manageTAs,
      RolePermission.createAnnouncements,
      RolePermission.createPost,
      RolePermission.viewProfile,
      RolePermission.editOwnProfile,
      RolePermission.viewNotifications,
    },
  ),

  UserRole.academicCoordinator: const RoleInfo(
    role: UserRole.academicCoordinator,
    category: RoleCategory.academicLeadership,
    nameEn: 'Academic Coordinator',
    nameAr: 'المنسق الأكاديمي',
    descriptionEn: 'Coordinates academic programs and scheduling',
    descriptionAr: 'تنسيق البرامج الأكاديمية والجداول',
    hierarchyLevel: 4,
    permissions: {
      RolePermission.manageCourses,
      RolePermission.manageSchedules,
      RolePermission.createAnnouncements,
      RolePermission.createPost,
      RolePermission.viewProfile,
      RolePermission.editOwnProfile,
      RolePermission.viewNotifications,
    },
  ),

  UserRole.professor: const RoleInfo(
    role: UserRole.professor,
    category: RoleCategory.teachingStaff,
    nameEn: 'Professor / Instructor',
    nameAr: 'عضو هيئة تدريس',
    descriptionEn: 'Faculty member who teaches and manages courses',
    descriptionAr: 'عضو هيئة تدريس يقوم بالتدريس وإدارة المقررات',
    hierarchyLevel: 3,
    permissions: {
      RolePermission.manageGrades,
      RolePermission.manageAttendance,
      RolePermission.createAnnouncements,
      RolePermission.createPost,
      RolePermission.uploadMaterials,
      RolePermission.manageTAs,
      RolePermission.manageGroups,
      RolePermission.accessForums,
      RolePermission.viewProfile,
      RolePermission.editOwnProfile,
      RolePermission.viewNotifications,
      RolePermission.submitSupportTicket,
    },
  ),

  UserRole.lecturer: const RoleInfo(
    role: UserRole.lecturer,
    category: RoleCategory.teachingStaff,
    nameEn: 'Lecturer',
    nameAr: 'محاضر',
    descriptionEn: 'Teaches courses without full professor privileges',
    descriptionAr: 'يقوم بالتدريس بدون صلاحيات الأستاذ الكاملة',
    hierarchyLevel: 4,
    permissions: {
      RolePermission.manageGrades,
      RolePermission.manageAttendance,
      RolePermission.createAnnouncements,
      RolePermission.createPost,
      RolePermission.uploadMaterials,
      RolePermission.accessForums,
      RolePermission.viewProfile,
      RolePermission.editOwnProfile,
      RolePermission.viewNotifications,
      RolePermission.submitSupportTicket,
    },
  ),

  UserRole.teachingAssistant: const RoleInfo(
    role: UserRole.teachingAssistant,
    category: RoleCategory.teachingStaff,
    nameEn: 'Teaching Assistant',
    nameAr: 'معيد / مساعد باحث',
    descriptionEn: 'Assists professors with grading, labs, and tutorials',
    descriptionAr: 'يساعد الأساتذة في التصحيح والمعامل والتمارين',
    hierarchyLevel: 5,
    permissions: {
      RolePermission.manageAttendance,
      RolePermission.uploadMaterials,
      RolePermission.accessForums,
      RolePermission.viewProfile,
      RolePermission.editOwnProfile,
      RolePermission.viewNotifications,
      RolePermission.submitSupportTicket,
    },
  ),

  UserRole.registrarOfficer: const RoleInfo(
    role: UserRole.registrarOfficer,
    category: RoleCategory.studentAffairs,
    nameEn: 'Registrar Officer',
    nameAr: 'مشرف القبول والتسجيل',
    descriptionEn: 'Manages student enrollment and registration',
    descriptionAr: 'إدارة قبول وتسجيل الطلاب',
    hierarchyLevel: 3,
    permissions: {
      RolePermission.manageEnrollments,
      RolePermission.approveEnrollments,
      RolePermission.viewProfile,
      RolePermission.editOwnProfile,
      RolePermission.viewNotifications,
      RolePermission.submitSupportTicket,
    },
  ),

  UserRole.academicAdvisor: const RoleInfo(
    role: UserRole.academicAdvisor,
    category: RoleCategory.studentAffairs,
    nameEn: 'Academic Advisor',
    nameAr: 'المرشد الأكاديمي',
    descriptionEn: 'Guides students through academic planning',
    descriptionAr: 'يرشد الطلاب خلال التخطيط الأكاديمي',
    hierarchyLevel: 4,
    permissions: {
      RolePermission.adviseStudents,
      RolePermission.viewGrades,
      RolePermission.viewSchedule,
      RolePermission.viewAttendance,
      RolePermission.viewProfile,
      RolePermission.editOwnProfile,
      RolePermission.viewNotifications,
      RolePermission.submitSupportTicket,
    },
  ),

  UserRole.librarian: const RoleInfo(
    role: UserRole.librarian,
    category: RoleCategory.studentAffairs,
    nameEn: 'Librarian',
    nameAr: 'أمين المكتبة',
    descriptionEn: 'Manages library resources and materials',
    descriptionAr: 'إدارة الموارد والمواد المكتبية',
    hierarchyLevel: 4,
    permissions: {
      RolePermission.manageLibrary,
      RolePermission.uploadMaterials,
      RolePermission.viewProfile,
      RolePermission.editOwnProfile,
      RolePermission.viewNotifications,
      RolePermission.submitSupportTicket,
    },
  ),

  UserRole.freshman: const RoleInfo(
    role: UserRole.freshman,
    category: RoleCategory.studentRoles,
    nameEn: 'Freshman',
    nameAr: 'طالب مستجد',
    descriptionEn: 'First-year student with limited system access',
    descriptionAr: 'طالب في السنة الأولى مع صلاحيات محدودة',
    hierarchyLevel: 7,
    permissions: {
      RolePermission.viewGrades,
      RolePermission.viewSchedule,
      RolePermission.viewAttendance,
      RolePermission.enrollCourses,
      RolePermission.viewFinance,
      RolePermission.viewMaterials,
      RolePermission.viewProfile,
      RolePermission.editOwnProfile,
      RolePermission.viewNotifications,
      RolePermission.submitSupportTicket,
    },
  ),

  UserRole.regularStudent: const RoleInfo(
    role: UserRole.regularStudent,
    category: RoleCategory.studentRoles,
    nameEn: 'Regular Student',
    nameAr: 'طالب منتظم',
    descriptionEn: 'Full student with all standard academic privileges',
    descriptionAr: 'طالب منتظم مع جميع الصلاحيات الأكاديمية المعتادة',
    hierarchyLevel: 6,
    permissions: {
      RolePermission.viewGrades,
      RolePermission.viewSchedule,
      RolePermission.viewAttendance,
      RolePermission.enrollCourses,
      RolePermission.viewFinance,
      RolePermission.submitRatings,
      RolePermission.accessForums,
      RolePermission.viewMaterials,
      RolePermission.viewProfile,
      RolePermission.editOwnProfile,
      RolePermission.viewNotifications,
      RolePermission.submitSupportTicket,
    },
  ),

  UserRole.student: const RoleInfo(
    role: UserRole.student,
    category: RoleCategory.studentRoles,
    nameEn: 'Student',
    nameAr: 'طالب',
    descriptionEn: 'General student role',
    descriptionAr: 'طالب عام',
    hierarchyLevel: 7,
    permissions: {
      RolePermission.viewGrades,
      RolePermission.viewSchedule,
      RolePermission.viewAttendance,
      RolePermission.enrollCourses,
      RolePermission.viewFinance,
      RolePermission.viewMaterials,
      RolePermission.viewProfile,
      RolePermission.editOwnProfile,
      RolePermission.viewNotifications,
      RolePermission.submitSupportTicket,
    },
  ),

  UserRole.classRepresentative: const RoleInfo(
    role: UserRole.classRepresentative,
    category: RoleCategory.studentRoles,
    nameEn: 'Class Representative',
    nameAr: 'رئيس الدفعة',
    descriptionEn: 'Student leader who represents the class body',
    descriptionAr: 'قائد طلابي يمثل مجموعته الدراسية',
    hierarchyLevel: 5,
    permissions: {
      RolePermission.viewGrades,
      RolePermission.viewSchedule,
      RolePermission.viewAttendance,
      RolePermission.enrollCourses,
      RolePermission.viewFinance,
      RolePermission.submitRatings,
      RolePermission.accessForums,
      RolePermission.viewMaterials,
      RolePermission.createAnnouncements,
      RolePermission.createPost,
      RolePermission.viewProfile,
      RolePermission.editOwnProfile,
      RolePermission.viewNotifications,
      RolePermission.submitSupportTicket,
    },
  ),

  UserRole.alumni: const RoleInfo(
    role: UserRole.alumni,
    category: RoleCategory.studentRoles,
    nameEn: 'Alumni',
    nameAr: 'خريج',
    descriptionEn: 'Graduated student with limited access',
    descriptionAr: 'طالب خريج مع صلاحيات محدودة',
    hierarchyLevel: 8,
    permissions: {
      RolePermission.viewGrades,
      RolePermission.accessForums,
      RolePermission.viewMaterials,
      RolePermission.viewProfile,
      RolePermission.editOwnProfile,
      RolePermission.viewNotifications,
      RolePermission.viewJobBoard,
    },
  ),

  UserRole.dormSupervisor: const RoleInfo(
    role: UserRole.dormSupervisor,
    category: RoleCategory.facilitiesSecurity,
    nameEn: 'Dorm Supervisor',
    nameAr: 'مشرف السكن',
    descriptionEn: 'Manages student dormitory operations',
    descriptionAr: 'إدارة عمليات السكن الطلابي',
    hierarchyLevel: 5,
    permissions: {
      RolePermission.viewProfile,
      RolePermission.editOwnProfile,
      RolePermission.viewNotifications,
      RolePermission.submitSupportTicket,
    },
  ),

  UserRole.securityOfficer: const RoleInfo(
    role: UserRole.securityOfficer,
    category: RoleCategory.facilitiesSecurity,
    nameEn: 'Security Officer',
    nameAr: 'مسؤول الأمن',
    descriptionEn: 'Campus security and access control',
    descriptionAr: 'أمن الحرم الجامعي والتحكم في الدخول',
    hierarchyLevel: 5,
    permissions: {
      RolePermission.viewProfile,
      RolePermission.viewNotifications,
      RolePermission.submitSupportTicket,
    },
  ),

  UserRole.guest: const RoleInfo(
    role: UserRole.guest,
    category: RoleCategory.facilitiesSecurity,
    nameEn: 'Guest',
    nameAr: 'زائر',
    descriptionEn: 'Temporary visitor with minimal access',
    descriptionAr: 'زائر مؤقت مع صلاحيات محدودة',
    hierarchyLevel: 10,
    permissions: {RolePermission.viewProfile},
  ),

  UserRole.parent: const RoleInfo(
    role: UserRole.parent,
    category: RoleCategory.externalRoles,
    nameEn: 'Parent / Guardian',
    nameAr: 'ولي الأمر',
    descriptionEn: 'Can view linked student progress and grades',
    descriptionAr: 'يمكنه متابعة تقدم الطالب المرتبط ودرجاته',
    hierarchyLevel: 8,
    permissions: {
      RolePermission.viewStudentProgress,
      RolePermission.viewGrades,
      RolePermission.viewAttendance,
      RolePermission.viewProfile,
      RolePermission.viewNotifications,
    },
  ),

  UserRole.recruiter: const RoleInfo(
    role: UserRole.recruiter,
    category: RoleCategory.externalRoles,
    nameEn: 'Recruiter',
    nameAr: 'جهة توظيف',
    descriptionEn: 'External recruitment organization',
    descriptionAr: 'جهة توظيف خارجية',
    hierarchyLevel: 9,
    permissions: {RolePermission.viewJobBoard, RolePermission.viewProfile},
  ),
};
