SELECT jsonb_build_object(
 'relations',(SELECT jsonb_agg(jsonb_build_object('name',c.relname,'kind',c.relkind,'partition',c.relispartition,'rls',c.relrowsecurity,'force',c.relforcerowsecurity,'comment',obj_description(c.oid),'columns',(SELECT jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'nullable',NOT a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid))) FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped),'constraints',(SELECT jsonb_agg(jsonb_build_object('name',conname,'type',contype,'definition',pg_get_constraintdef(oid),'validated',convalidated)) FROM pg_constraint WHERE conrelid=c.oid),'indexes',(SELECT jsonb_agg(indexdef) FROM pg_indexes WHERE schemaname='public' AND tablename=c.relname),'policies',(SELECT jsonb_agg(to_jsonb(p)) FROM pg_policies p WHERE schemaname='public' AND tablename=c.relname),'grants',(SELECT jsonb_agg(to_jsonb(g)) FROM information_schema.role_table_grants g WHERE table_schema='public' AND table_name=c.relname),'view',CASE WHEN c.relkind IN ('v','m') THEN pg_get_viewdef(c.oid) END)) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN ('r','p','v','m')),
 'functions',(SELECT jsonb_agg(jsonb_build_object('name',p.proname,'signature',p.oid::regprocedure::text,'result',pg_get_function_result(p.oid),'definer',p.prosecdef,'config',p.proconfig,'volatility',p.provolatile,'acl',p.proacl,'definition',pg_get_functiondef(p.oid),'extension',e.extname)) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace LEFT JOIN pg_depend d ON d.objid=p.oid AND d.deptype='e' LEFT JOIN pg_extension e ON e.oid=d.refobjid WHERE n.nspname='public'),
 'triggers',(SELECT jsonb_agg(jsonb_build_object('table',t.tgrelid::regclass::text,'name',t.tgname,'definition',pg_get_triggerdef(t.oid))) FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE NOT t.tgisinternal AND n.nspname IN ('public','auth')),
 'enums',(SELECT jsonb_agg(to_jsonb(x)) FROM (SELECT t.typname,array_agg(e.enumlabel ORDER BY e.enumsortorder) labels FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace JOIN pg_enum e ON e.enumtypid=t.oid WHERE n.nspname='public' GROUP BY t.typname) x),
 'buckets',(SELECT jsonb_agg(to_jsonb(b)) FROM storage.buckets b),
 'storage_policies',(SELECT jsonb_agg(to_jsonb(p)) FROM pg_policies p WHERE schemaname='storage'),
 'publication',(SELECT jsonb_agg(to_jsonb(p)) FROM pg_publication_tables p),
 'column_grants',(SELECT jsonb_agg(to_jsonb(g)) FROM information_schema.column_privileges g WHERE table_schema='public' AND grantee IN ('PUBLIC','anon','authenticated')),
 'rbac',(SELECT jsonb_agg(to_jsonb(x)) FROM (SELECT r.code,array_agg(p.code ORDER BY p.code) FILTER (WHERE p.id IS NOT NULL) permissions FROM public.role_definitions r LEFT JOIN public.role_permissions rp ON rp.role_id=r.id LEFT JOIN public.permissions p ON p.id=rp.permission_id GROUP BY r.code) x)
);
