-- ╔══════════════════════════════════════════════════════════════════╗
-- ║              HUE University Portal — Supabase Schema            ║
-- ║                   Version 1.0 — Full Production                 ║
-- ╚══════════════════════════════════════════════════════════════════╝
--
-- This file is a REFERENCE COPY of all database tables.
-- It is NOT executed by the app — it exists purely for documentation.
--
-- Architecture Principles:
--   • Row Level Security (RLS) on every table
--   • UUID primary keys (generated by Supabase auth or gen_random_uuid())
--   • Soft-delete via `deleted_at` timestamps
--   • Audit trail via `created_at` / `updated_at`
--   • Normalized relationships with foreign keys
--   • Encrypted sensitive fields at the application layer (not DB level)
--   • Modular: each feature maps to a distinct table group

-- ─────────────────────────────────────────────────
-- 0. EXTENSIONS
-- ─────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "pgcrypto";    -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "moddatetime"; -- auto-update updated_at

-- ─────────────────────────────────────────────────
-- 1. ENUMS
-- ─────────────────────────────────────────────────
CREATE TYPE user_role AS ENUM (
  -- Admin & IT
  'super_admin', 'it_support', 'financial_auditor',
  -- Academic Leadership
  'rector', 'dean', 'department_head', 'academic_coordinator',
  -- Teaching Staff
  'professor', 'lecturer', 'teaching_assistant',
  -- Student Affairs
  'registrar_officer', 'academic_advisor', 'librarian',
  -- Student Roles
  'freshman', 'regular_student', 'class_representative', 'alumni',
  -- Facilities & Security
  'dorm_supervisor', 'security_officer', 'guest',
  -- External Roles
  'parent', 'recruiter'
);
CREATE TYPE announcement_priority AS ENUM ('normal', 'important', 'urgent');
CREATE TYPE enrollment_status AS ENUM ('pending', 'approved', 'rejected', 'withdrawn');
CREATE TYPE payment_status AS ENUM ('pending', 'paid', 'overdue', 'refunded');
CREATE TYPE attendance_status AS ENUM ('present', 'absent', 'late', 'excused');
CREATE TYPE notification_type AS ENUM ('info', 'warning', 'success', 'error');
CREATE TYPE file_type AS ENUM ('pdf', 'docx', 'pptx', 'xlsx', 'image', 'video', 'other');
CREATE TYPE day_of_week AS ENUM ('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday');
CREATE TYPE session_device AS ENUM ('mobile', 'desktop', 'tablet', 'unknown');
CREATE TYPE forum_category AS ENUM ('general', 'academic', 'social', 'feedback');
CREATE TYPE support_ticket_status AS ENUM ('open', 'in_progress', 'resolved', 'closed');

-- ═══════════════════════════════════════════════════
-- 2. CORE: USER PROFILES
-- ═══════════════════════════════════════════════════

CREATE TABLE profiles (
  id            UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email         TEXT NOT NULL UNIQUE,
  full_name     TEXT NOT NULL,
  full_name_ar  TEXT,                        -- Arabic name
  avatar_url    TEXT,
  role          user_role NOT NULL DEFAULT 'student',
  student_id    TEXT UNIQUE,                 -- e.g., "20201234"
  phone         TEXT,
  bio           TEXT,
  bio_ar        TEXT,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at    TIMESTAMPTZ
);

-- Auto-update updated_at
CREATE TRIGGER profiles_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION moddatetime(updated_at);

-- RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view all active profiles"
  ON profiles FOR SELECT USING (deleted_at IS NULL);
CREATE POLICY "Users can update own profile"
  ON profiles FOR UPDATE USING (auth.uid() = id);

-- ═══════════════════════════════════════════════════
-- 3. ACADEMIC: COLLEGES & DEPARTMENTS
-- ═══════════════════════════════════════════════════

CREATE TABLE colleges (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name          TEXT NOT NULL,
  name_ar       TEXT NOT NULL,
  code          TEXT NOT NULL UNIQUE,         -- e.g., "FCAI"
  description   TEXT,
  description_ar TEXT,
  dean_id       UUID REFERENCES profiles(id),
  image_url     TEXT,
  established   INT,
  student_count INT DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE colleges ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view colleges" ON colleges FOR SELECT USING (TRUE);

CREATE TABLE departments (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  college_id    UUID NOT NULL REFERENCES colleges(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  name_ar       TEXT NOT NULL,
  code          TEXT NOT NULL UNIQUE,
  hod_id        UUID REFERENCES profiles(id), -- Head of Department
  description   TEXT,
  description_ar TEXT,
  office_symbol TEXT,
  floor         INT,
  building      TEXT,
  student_count INT DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE departments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view departments" ON departments FOR SELECT USING (TRUE);

-- ═══════════════════════════════════════════════════
-- 4. ACADEMIC: COURSES
-- ═══════════════════════════════════════════════════

CREATE TABLE courses (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  department_id   UUID NOT NULL REFERENCES departments(id) ON DELETE CASCADE,
  code            TEXT NOT NULL UNIQUE,       -- e.g., "CS301"
  name            TEXT NOT NULL,
  name_ar         TEXT NOT NULL,
  description     TEXT,
  credit_hours    INT NOT NULL DEFAULT 3,
  semester        TEXT,                       -- e.g., "Fall 2025"
  professor_id    UUID REFERENCES profiles(id),
  max_students    INT DEFAULT 50,
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view active courses" ON courses FOR SELECT USING (is_active = TRUE);

-- ═══════════════════════════════════════════════════
-- 5. ENROLLMENT: STUDENT-COURSE REGISTRATION
-- ═══════════════════════════════════════════════════

CREATE TABLE enrollments (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id    UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  course_id     UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  status        enrollment_status NOT NULL DEFAULT 'pending',
  semester      TEXT NOT NULL,
  enrolled_at   TIMESTAMPTZ DEFAULT now(),
  approved_at   TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(student_id, course_id, semester)
);

ALTER TABLE enrollments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Students can view own enrollments"
  ON enrollments FOR SELECT USING (auth.uid() = student_id);
CREATE POLICY "Admins can manage enrollments"
  ON enrollments FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- Course sections (A, B, C...)
CREATE TABLE course_sections (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  course_id    UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  name         TEXT NOT NULL,           -- e.g., 'A', 'B'
  semester     TEXT NOT NULL,
  max_students INT DEFAULT 50,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE course_sections ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view sections" ON course_sections FOR SELECT USING (TRUE);

-- Sub-sections (A1, A2, A3, A4...)
CREATE TABLE course_sub_sections (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  section_id   UUID NOT NULL REFERENCES course_sections(id) ON DELETE CASCADE,
  name         TEXT NOT NULL,          -- e.g., 'A1', 'A2'
  max_students INT DEFAULT 25,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE course_sub_sections ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view sub_sections" ON course_sub_sections FOR SELECT USING (TRUE);

-- Student registration: links student → section + sub_section (applied to whole semester)
CREATE TABLE student_registrations (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id       UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  semester         TEXT NOT NULL,
  section_name     TEXT NOT NULL,       -- e.g., 'A'
  sub_section_name TEXT NOT NULL,       -- e.g., 'A1'
  registered_at    TIMESTAMPTZ DEFAULT now(),
  UNIQUE(student_id, semester)
);

ALTER TABLE student_registrations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Students can view own registrations"
  ON student_registrations FOR SELECT USING (auth.uid() = student_id);
CREATE POLICY "Students can insert own registrations"
  ON student_registrations FOR INSERT WITH CHECK (auth.uid() = student_id);
CREATE POLICY "Admins can manage registrations"
  ON student_registrations FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- ═══════════════════════════════════════════════════
-- 6. ACADEMIC: GRADES & TRANSCRIPT
-- ═══════════════════════════════════════════════════

CREATE TABLE grades (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id    UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  course_id     UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  semester      TEXT NOT NULL,
  midterm       NUMERIC(5,2),
  final_exam    NUMERIC(5,2),
  coursework    NUMERIC(5,2),
  practical     NUMERIC(5,2),
  total         NUMERIC(5,2),
  grade_letter  TEXT,                        -- A+, A, B+, ...
  gpa_points    NUMERIC(3,2),
  is_published  BOOLEAN NOT NULL DEFAULT FALSE,
  published_at  TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(student_id, course_id, semester)
);

ALTER TABLE grades ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Students can view own grades"
  ON grades FOR SELECT USING (auth.uid() = student_id AND is_published = TRUE);
CREATE POLICY "Professors can manage grades"
  ON grades FOR ALL USING (
    EXISTS (
      SELECT 1 FROM courses c
      WHERE c.id = grades.course_id AND c.professor_id = auth.uid()
    )
  );

-- ═══════════════════════════════════════════════════
-- 7. ACADEMIC: SCHEDULES
-- ═══════════════════════════════════════════════════

CREATE TABLE schedules (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  course_id     UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  day           day_of_week NOT NULL,
  start_time    TIME NOT NULL,
  end_time      TIME NOT NULL,
  room          TEXT,
  building      TEXT,
  schedule_type TEXT DEFAULT 'lecture',       -- lecture, lab, tutorial
  semester      TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view schedules" ON schedules FOR SELECT USING (TRUE);

-- Exam schedules (separate for flexibility)
CREATE TABLE exam_schedules (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  course_id     UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  exam_type     TEXT NOT NULL DEFAULT 'final', -- midterm, final, quiz
  exam_date     DATE NOT NULL,
  start_time    TIME NOT NULL,
  end_time      TIME NOT NULL,
  room          TEXT,
  building      TEXT,
  semester      TEXT NOT NULL,
  notes         TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE exam_schedules ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view exam schedules" ON exam_schedules FOR SELECT USING (TRUE);

-- ═══════════════════════════════════════════════════
-- 8. ACADEMIC: ATTENDANCE
-- ═══════════════════════════════════════════════════

CREATE TABLE attendance (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id    UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  course_id     UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  date          DATE NOT NULL,
  status        attendance_status NOT NULL DEFAULT 'present',
  notes         TEXT,
  recorded_by   UUID REFERENCES profiles(id),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(student_id, course_id, date)
);

ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Students can view own attendance"
  ON attendance FOR SELECT USING (auth.uid() = student_id);

-- ═══════════════════════════════════════════════════
-- 9. ACADEMIC: PROFESSOR PROFILES & OFFICE HOURS
-- ═══════════════════════════════════════════════════

CREATE TABLE professor_details (
  id                UUID PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
  department_id     UUID REFERENCES departments(id),
  office_symbol     TEXT,
  general_rating    NUMERIC(3,2) DEFAULT 0,
  curriculum_rating NUMERIC(3,2) DEFAULT 0,
  total_ratings     INT DEFAULT 0,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE professor_details ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view professor details"
  ON professor_details FOR SELECT USING (TRUE);

CREATE TABLE office_hours (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  professor_id  UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  day           day_of_week NOT NULL,
  start_time    TIME NOT NULL,
  end_time      TIME NOT NULL,
  location      TEXT NOT NULL,
  is_walk_in    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE office_hours ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view office hours" ON office_hours FOR SELECT USING (TRUE);

-- ═══════════════════════════════════════════════════
-- 10. ACADEMIC: TEACHING ASSISTANTS
-- ═══════════════════════════════════════════════════

CREATE TABLE teaching_assistants (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id    UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  professor_id  UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  ta_role       TEXT DEFAULT 'Lab Assistant', -- Lead TA, Grading, etc.
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(profile_id, professor_id)
);

ALTER TABLE teaching_assistants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view TAs" ON teaching_assistants FOR SELECT USING (TRUE);

-- ═══════════════════════════════════════════════════
-- 11. ACADEMIC: STUDENT GROUPS
-- ═══════════════════════════════════════════════════

CREATE TABLE student_groups (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  professor_id  UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  course_id     UUID REFERENCES courses(id),
  name          TEXT NOT NULL,
  name_ar       TEXT,
  description   TEXT,
  max_students  INT DEFAULT 50,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE student_groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view active groups"
  ON student_groups FOR SELECT USING (is_active = TRUE);

CREATE TABLE group_members (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  group_id      UUID NOT NULL REFERENCES student_groups(id) ON DELETE CASCADE,
  student_id    UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  joined_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(group_id, student_id)
);

ALTER TABLE group_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Group members can view their groups"
  ON group_members FOR SELECT USING (auth.uid() = student_id);

-- ═══════════════════════════════════════════════════
-- 12. ANNOUNCEMENTS
-- ═══════════════════════════════════════════════════

CREATE TABLE announcements (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  author_id     UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  course_id     UUID REFERENCES courses(id),  -- NULL = global announcement
  title         TEXT NOT NULL,
  title_ar      TEXT,
  content       TEXT NOT NULL,
  content_ar    TEXT,
  priority      announcement_priority NOT NULL DEFAULT 'normal',
  is_pinned     BOOLEAN NOT NULL DEFAULT FALSE,
  published_at  TIMESTAMPTZ DEFAULT now(),
  expires_at    TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at    TIMESTAMPTZ
);

ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view active announcements"
  ON announcements FOR SELECT USING (deleted_at IS NULL);

-- ═══════════════════════════════════════════════════
-- 13. SHARED FILES / MATERIALS
-- ═══════════════════════════════════════════════════

CREATE TABLE shared_files (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  uploader_id   UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  course_id     UUID REFERENCES courses(id),
  title         TEXT NOT NULL,
  title_ar      TEXT,
  file_path     TEXT NOT NULL,               -- Supabase Storage path
  file_type     file_type NOT NULL DEFAULT 'other',
  file_size     BIGINT,                      -- bytes
  download_count INT DEFAULT 0,
  is_public     BOOLEAN DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at    TIMESTAMPTZ
);

ALTER TABLE shared_files ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view public files"
  ON shared_files FOR SELECT USING (is_public = TRUE AND deleted_at IS NULL);

-- ═══════════════════════════════════════════════════
-- 14. FINANCE: INVOICES & PAYMENTS
-- ═══════════════════════════════════════════════════

CREATE TABLE invoices (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id    UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  semester      TEXT NOT NULL,
  description   TEXT NOT NULL,
  description_ar TEXT,
  amount        NUMERIC(10,2) NOT NULL,
  currency      TEXT NOT NULL DEFAULT 'EGP',
  status        payment_status NOT NULL DEFAULT 'pending',
  due_date      DATE,
  paid_at       TIMESTAMPTZ,
  receipt_url   TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Students can view own invoices"
  ON invoices FOR SELECT USING (auth.uid() = student_id);

-- ═══════════════════════════════════════════════════
-- 15. NOTIFICATIONS
-- ═══════════════════════════════════════════════════

CREATE TABLE notifications (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title         TEXT NOT NULL,
  title_ar      TEXT,
  message       TEXT NOT NULL,
  message_ar    TEXT,
  type          notification_type NOT NULL DEFAULT 'info',
  is_read       BOOLEAN NOT NULL DEFAULT FALSE,
  action_url    TEXT,                        -- deep link path
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  read_at       TIMESTAMPTZ
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own notifications"
  ON notifications FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own notifications"
  ON notifications FOR UPDATE USING (auth.uid() = user_id);

-- ═══════════════════════════════════════════════════
-- 16. FORUMS
-- ═══════════════════════════════════════════════════

CREATE TABLE forums (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name          TEXT NOT NULL,
  name_ar       TEXT,
  description   TEXT,
  category      forum_category NOT NULL DEFAULT 'general',
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE forums ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view forums" ON forums FOR SELECT USING (is_active = TRUE);

CREATE TABLE forum_posts (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  forum_id      UUID NOT NULL REFERENCES forums(id) ON DELETE CASCADE,
  author_id     UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title         TEXT NOT NULL,
  content       TEXT NOT NULL,
  is_pinned     BOOLEAN DEFAULT FALSE,
  reply_count   INT DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at    TIMESTAMPTZ
);

ALTER TABLE forum_posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view posts" ON forum_posts FOR SELECT USING (deleted_at IS NULL);

-- ═══════════════════════════════════════════════════
-- 17. SUPPORT TICKETS
-- ═══════════════════════════════════════════════════

CREATE TABLE support_tickets (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  subject       TEXT NOT NULL,
  description   TEXT NOT NULL,
  category      TEXT DEFAULT 'general',
  status        support_ticket_status NOT NULL DEFAULT 'open',
  assigned_to   UUID REFERENCES profiles(id),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at   TIMESTAMPTZ
);

ALTER TABLE support_tickets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own tickets"
  ON support_tickets FOR SELECT USING (auth.uid() = user_id);

-- ═══════════════════════════════════════════════════
-- 18. USER SESSIONS (Device Management)
-- ═══════════════════════════════════════════════════

CREATE TABLE user_sessions (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  device_name   TEXT,
  device_type   session_device DEFAULT 'unknown',
  ip_address    INET,
  location      TEXT,
  user_agent    TEXT,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  last_active   TIMESTAMPTZ DEFAULT now(),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE user_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own sessions"
  ON user_sessions FOR SELECT USING (auth.uid() = user_id);

-- ═══════════════════════════════════════════════════
-- 19. PROFESSOR RATINGS
-- ═══════════════════════════════════════════════════

CREATE TABLE professor_ratings (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  professor_id    UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  student_id      UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  general_score   INT NOT NULL CHECK (general_score BETWEEN 1 AND 5),
  curriculum_score INT NOT NULL CHECK (curriculum_score BETWEEN 1 AND 5),
  comment         TEXT,
  is_anonymous    BOOLEAN DEFAULT TRUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(professor_id, student_id)
);

ALTER TABLE professor_ratings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view ratings"
  ON professor_ratings FOR SELECT USING (TRUE);
CREATE POLICY "Students can rate professors"
  ON professor_ratings FOR INSERT WITH CHECK (auth.uid() = student_id);

-- ═══════════════════════════════════════════════════
-- 20. ACTION PLAN (DEGREE TRACKING)
-- ═══════════════════════════════════════════════════

CREATE TABLE action_plan_items (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id    UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  course_id     UUID REFERENCES courses(id),
  semester      TEXT NOT NULL,
  year          INT NOT NULL,
  status        TEXT DEFAULT 'planned',       -- planned, in_progress, completed, failed
  grade_letter  TEXT,
  notes         TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE action_plan_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Students can view own action plan"
  ON action_plan_items FOR SELECT USING (auth.uid() = student_id);

-- ═══════════════════════════════════════════════════
-- 21. INDEXES FOR PERFORMANCE
-- ═══════════════════════════════════════════════════

CREATE INDEX idx_enrollments_student ON enrollments(student_id);
CREATE INDEX idx_enrollments_course ON enrollments(course_id);
CREATE INDEX idx_grades_student ON grades(student_id);
CREATE INDEX idx_grades_course ON grades(course_id);
CREATE INDEX idx_attendance_student ON attendance(student_id);
CREATE INDEX idx_attendance_course ON attendance(course_id);
CREATE INDEX idx_schedules_course ON schedules(course_id);
CREATE INDEX idx_notifications_user ON notifications(user_id, is_read);
CREATE INDEX idx_announcements_course ON announcements(course_id);
CREATE INDEX idx_invoices_student ON invoices(student_id);
CREATE INDEX idx_forum_posts_forum ON forum_posts(forum_id);
CREATE INDEX idx_shared_files_course ON shared_files(course_id);
CREATE INDEX idx_action_plan_student ON action_plan_items(student_id);

-- ═══════════════════════════════════════════════════
-- END OF SCHEMA
-- ═══════════════════════════════════════════════════
